### ISSUE TITLE
general comments about the code structure

### ISSUE THREAD

**Issue by eviljeff** [mozilla/assay#2]
- Are you planning to keep the changelog up to date?  It's not super important to have - `web-ext` just includes any significant changes in the `Release` in github, and the commit log should be enough to cover more detailed changes.
https://github.com/mozilla/assay/blob/ed052d80e7c6aa323cad1956eb192ea522c38a22/CHANGELOG.md?plain=1#L5

- Are the files in `/.vscode` customized by you/this extension?  I couldn't see anything obviously wrong there but I'm not familiar with what the defaults/boilerplate would be.

- I think we can flatten `/src/amo` into just `/src` and move `tests` to the top level - the frontend repo does a few different things (it can be build as a standalone blog utils library, for example) but in general we don't need the extra extraction (at this point, anyway)

- imo, use `type`s everywhere, rather than `interface`s but I don't know if @diox has opinions on that.

- can we add a linting rule for import order?  it makes the codebase a little easier to follow (maybe not so much of a problem right now, but after it's grown)

**Comment by GregSherman** [comment]
1. I think the changelog was auto added when vscode made the extension template. I had forgotten it was there. I will remove it and keep notable changes in the release
2. the folder was created with the template, but I did end up changing launch.json to edit the run command. It can also add in more commands to the green play button area if needed.
3. Sure
4. Also sure
5. Yes I was thinking that too as well as fixing the lint command since it hasn't been working for me.
