### ISSUE TITLE
Allow files to be modified

### ISSUE THREAD

**Issue by abyrne-moz** [mozilla/assay#88]
Allow version files opened by Assay to be editable by reviewers.  They often edit files to assist with investigation and debugging.

https://github.com/mozilla/assay/commit/faefe8d3323b699d90d4f60093430561a8e0b21a

**Comment by chrstinalin** [comment]
The problem with allowing version files to be editable is that linting results are fetched from an API endpoint [/reviewers/addon/<addon_id>/file/<file_id>/validation/](https://github.com/diox/olympia/blob/9eaed4d5924ec9e9ef180ef3579c38004269d392/docs/topics/api/reviewers.rst#file-validation), which means files and line numbers are all synced with the copy that was linted.

Any changes such as deleting a line would cause VS Code to highlight the wrong lines (ex. line 24 is linted, but I delete two lines before that. Now, the original line 26 is on line 24, but is highlighted with line 24's issue).

We originally went down the path of live linting by directly integrating `addons-linter` into Assay (and even its own extension), but faced several blockers along the way:

1.  VS Code, by design, will lint by individual file rather than the entire version (which `addons-linter` requires, as some lints depend on the existence of files in the version).
2. Linting the entire version every time a change is made causes a notable amount of lag. `addons-linter` could originally lint by file, but was unable to resolve references to other files (making its lints incorrect), and that functionality has since been [removed](https://github.com/mozilla/addons-linter/issues/5319).

A possible fix would be to disable lints when the file is modified,  but that removes any information you would get from the linter. Maybe an 'override' to the read-only policy with a warning?

**Comment by abyrne-moz** [comment]
@willdurand confirmed that it is OK for the linter to be incorrect when a reviewer changes the file.  Disabling the linter when a file is edited would probably be a good solution.

@wagnerand - do you agree?

**Comment by wagnerand** [comment]
Agreed.
