### ISSUE TITLE
Allow Assay to connect to Prod, Stage and Dev environments

### ISSUE THREAD

**Issue by abyrne-moz** [mozilla/assay#91]
Provide functionality for a reviewer to decide which environment Assay opens and connects to
1. Production
2. Stage
3. Dev

**Comment by chrstinalin** [comment]
Switching between environments may not work out since the databases are different.

For example, take I install add-on with ID 64 in dev, and I then switch to stage. That ID may point to a different add-on now. This is likely to confuse Assay -- for one, since linter messages are actively fetched by ID, the fetched results may not exist or be for a different add-on entirely.

For more context, in which scenarios is this utilized?

**Comment by abyrne-moz** [comment]
I think the goal would be to "open VSCode + Assay" connected to an environment for that particular session, or at least open it and have it connect to the last environment you connected to.  I don't believe that a reviewer will switch environments mid review.

This is so that if a bug is found in Assay or a reviewer wants to test something, they can easily connect to a different environment to complete that test or validate a bug.

**Comment by chrstinalin** [comment]
(Discussed this further on Slack) Since the context is to open Assay in Dev/Stage just to validate any bugs they find or test things, note that this is already possible by building Assay from the source code (and all they'd need to do is follow the instructions in the README.MD). 
![image](https://github.com/user-attachments/assets/3b915c31-3bdd-4b78-bfda-d502da1e7d36)

However, VS Code will sync settings across any versions of the extension, so the aforementioned problem still exists (any add-ons you installed in production will still exist in the development environment unless you manually change the addons root folder in settings.)

@willdurand @wagnerand for visibility
